version: '3'

services:

  adguard:
    image: adguard/adguardhome
    restart: unless-stopped
    ports:
      # uncomment ports below if you're going to use them
      # more info about ports: https://github.com/AdguardTeam/AdGuardHome/wiki/Docker
      - 53:53/tcp		# for DNS
      - 53:53/udp		# for DNS
      #- 67:67/udp
      #- 853:853/tcp
      #- 853:853/udp
      #- 5443:5443/tcp
      #- 5443:5443/udp
      #- 8853:8853/udp
      - 3000:3000/tcp		# adguard initial config
      - 3001:3001/tcp		# adguard admin interface
      #- 443:443/tcp
      #- 443:443/udp
      #- 784:784/udp

    volumes:
      - ${LOCAL_DIR}/work:/opt/adguardhome/work
      - ${LOCAL_DIR}/conf:/opt/adguardhome/conf
    container_name: adguardhome
