version: '3'

services:

  adguard:
    image: adguard/adguardhome
    restart: unless-stopped
    network_mode: "host"
    ports:
	# more info about ports: https://github.com/AdguardTeam/AdGuardHome/wiki/Docker
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 853:853/tcp
      - 853:853/udp
      - 5443:5443/tcp
      - 5443:5443/udp
      - 8853:8853/udp
      - 3000:3000/tcp
      - 3001:3001/tcp
      - 443:443/tcp
      - 443:443/udp
      - 784:784/udp

    volumes:
      - /home/rpi42gb/adguardhome/work:/opt/adguardhome/work
      - /home/rpi42gb/adguardhome/conf:/opt/adguardhome/conf
    container_name: adguardhome
